--EX 1
--CONCLUIDO
USE LMS

--EX 2
--CONCLUIDO
SELECT P.NOME AS NOME_PROFESSOR,D.NOME AS NOME_DISCIPLINA, A.NOME AS NOME_ALUNO, A.RA
FROM DISCIPLINAOFERTADA DO
JOIN PROFESSOR P ON P.ID = DO.IDPROFESSOR
JOIN DISCIPLINA D ON DO.IDDISCIPLINA = D.ID
JOIN SOLICITACAOMATRICULA SM ON SM.ID = DO.ID
JOIN ALUNO A ON A.ID = SM.IDALUNO

--EX 3
--CONCLUIDO
SELECT DISCIPLINA.NOME, DISCIPLINA.STATUS FROM DISCIPLINA
WHERE STATUS = 'ABERTA'
ORDER BY NOME


--EX 4

SELECT * FROM ENTREGA
ORDER BY IDALUNO
SELECT A.NOME, A.ID, E.TITULO FROM ALUNO A 
JOIN ENTREGA E ON E.IDALUNO != A.ID
WHERE STATUS != 'CORRIGIDO' AND STATUS != 'ENTREGUE'

--EX 5
--Trabalhos entregues e não corrigidos pelo professor
--CONCLUIDO
SELECT TITULO, ISNULL(NOTA, 0) AS NOTA, STATUS FROM ENTREGA
WHERE STATUS = 'ENTREGUE'

--EX 6
--Disciplinas ofertadas mas ainda sem professor
--CONCLUIDO
SELECT D.NOME, ISNULL(IDPROFESSOR, 0) AS IDPROFESSOR FROM DISCIPLINAOFERTADA DO
JOIN DISCIPLINA D ON D.ID = DO.IDDISCIPLINA
WHERE IDPROFESSOR = 0


--EX 7
SELECT COUNT(A.NOME), D.NOME FROM ALUNO A
JOIN SOLICITACAOMATRICULA SM ON SM.IDALUNO = A.ID
JOIN DISCIPLINA D ON SM.IDDOFERTADA = D.ID
GROUP BY D.NOME



--EX 8
SELECT A.NOME,
(SELECT ISNULL(NOTA, 0) FROM ENTREGA WHERE IDAVINCULADA = 1 AND STATUS IN ('CORRIGIDO') AND IDALUNO = 1) AS AC1,
(SELECT ISNULL(NOTA, 0) FROM ENTREGA WHERE IDAVINCULADA = 2 AND STATUS IN ('CORRIGIDO') AND IDALUNO = 1) AS AC2,
(SELECT ISNULL(NOTA, 0) FROM ENTREGA WHERE IDAVINCULADA = 3 AND STATUS IN ('CORRIGIDO') AND IDALUNO = 1) AS AC3,
(SELECT ISNULL(NOTA, 0) FROM ENTREGA WHERE IDAVINCULADA = 4 AND STATUS IN ('CORRIGIDO') AND IDALUNO = 1) AS AC4,
(SELECT ISNULL(NOTA, 0) FROM ENTREGA WHERE IDAVINCULADA = 5 AND STATUS IN ('CORRIGIDO') AND IDALUNO = 1) AS AC5,
(SELECT ISNULL(NOTA, 0) FROM ENTREGA WHERE IDAVINCULADA = 6 AND STATUS IN ('CORRIGIDO') AND IDALUNO = 1) AS AC6,
(SELECT ISNULL(NOTA, 0) FROM ENTREGA WHERE IDAVINCULADA = 7 AND STATUS IN ('CORRIGIDO') AND IDALUNO = 1) AS AC7,
(SELECT ISNULL(NOTA, 0) FROM ENTREGA WHERE IDAVINCULADA = 8 AND STATUS IN ('CORRIGIDO') AND IDALUNO = 1) AS AC8,
(SELECT ISNULL(NOTA, 0) FROM ENTREGA WHERE IDAVINCULADA = 9 AND STATUS IN ('CORRIGIDO') AND IDALUNO = 1) AS AC9,
(SELECT ISNULL(NOTA, 0) FROM ENTREGA WHERE IDAVINCULADA = 10 AND STATUS IN ('CORRIGIDO') AND IDALUNO = 1) AS AC10
FROM ALUNO AS A FULL OUTER JOIN ENTREGA AS E
ON A.ID = E.IDALUNO
GROUP BY A.NOME

--EX 9



--EX 10
