--EX 1
--CONCLUIDO
USE LMS

--EX 2
--CONCLUIDO
SELECT P.NOME AS NOME_PROFESSOR,D.NOME AS NOME_DISCIPLINA, A.NOME AS NOME_ALUNO, A.RA
FROM DISCIPLINAOFERTADA DO
JOIN PROFESSOR P ON P.ID = DO.IDPROFESSOR
JOIN DISCIPLINA D ON DO.IDDISCIPLINA = D.ID
JOIN SOLICITACAOMATRICULA SM ON SM.ID = DO.ID
JOIN ALUNO A ON A.ID = SM.IDALUNO

--EX 3
--CONCLUIDO
SELECT DISCIPLINA.NOME, DISCIPLINA.STATUS FROM DISCIPLINA
WHERE STATUS = 'ABERTA'
ORDER BY NOME


--EX 4



--EX 5
--Trabalhos entregues e não corrigidos pelo professor
--CONCLUIDO
SELECT TITULO, ISNULL(NOTA, 0) AS NOTA, STATUS FROM ENTREGA
WHERE STATUS = 'ENTREGUE'

--EX 6
--Disciplinas ofertadas mas ainda sem professor
--CONCLUIDO
SELECT D.NOME, ISNULL(IDPROFESSOR, 0) AS IDPROFESSOR FROM DISCIPLINAOFERTADA DO
JOIN DISCIPLINA D ON D.ID = DO.IDDISCIPLINA
WHERE IDPROFESSOR = 0


--EX 7
SELECT COUNT(A.NOME) FROM ALUNO A

SELECT * FROM SOLICITACAOMATRICULA
SELECT * FROM DISCIPLINAOFERTADA


--EX 8
SELECT [ENTREGA AC1],[ENTREGA AC2], [ENTREGA AC3], [ENTREGA AC4], [ENTREGA AC5] FROM ENTREGA E
PIVOT(SUM(NOTA) FOR TITULO IN ([ENTREGA AC1],[ENTREGA AC2], [ENTREGA AC3], [ENTREGA AC4], [ENTREGA AC5])) AS PVT

SELECT A.NOME,E.TITULO,E.NOTA FROM ALUNO A
JOIN ENTREGA E ON E.IDALUNO = A.ID


--EX 9
CREATE VIEW VW_TESTE
AS


--EX 10
